### ISSUE TITLE
Dimensione font dialog registrazione/login

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#1]
Sarebbe comodo avere il font dei campi delle dialog registrazione/login di qualche punto più grande, per facilitare la lettura

**Comment by AlexandroVassallo** [comment]
Ci lavoro subito

**Comment by AlexandroVassallo** [comment]
Fixato

**Comment by SalvoRusso8** [comment]
Piccoli aggiustamenti da fare, ma verificato
