### ISSUE TITLE
Problemi nella dialog "crea corso"

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#10]
1) L'elenco dei suggerimenti dei professori del corso deve comparire quando si fa click sulla riga di inserimento, anche prima di cominciare a digitare.
2) Aumentare la larghezza della dialog così da avere più spazio per visualizzare i nomi dei docenti
3) Pulire la riga di inserimento dopo aver selezionato un docente
4) Segnalare in rosso "Seleziona foto iniziale VM" se non viene selezionata un'immagine prima di procedere

**Comment by SalvoRusso8** [comment]
Il problema numero 1 è presente anche nell'aggiunta degli studenti al corso

**Comment by ValeMargi** [comment]
Punti 1,3 risolti.
Andrebbe aggiustato il punto 2, ovvero allargare la finestra con l'elenco dei professori
![image](https://user-images.githubusercontent.com/52396149/97588535-e0dd8900-19fc-11eb-89de-55ea123ddf11.png)

Manca punto 4, non viene segnalato in rosso "Seleziona foto iniziale VM"  ma compare un alert generico "Controllare di aver inserito tutti i dati richiesti e riprovare"

**Comment by jackgorga** [comment]
Il punto 4 hai ragione, il punto 2 avevo capito la tabella, non l'autocomplete, farò anche quello

**Comment by ValeMargi** [comment]
> Il punto 4 hai ragione, il punto 2 avevo capito la tabella, non l'autocomplete, farò anche quello

Sì hai ragione scusa non era chiarissimo il punto 2

**Comment by AlexandroVassallo** [comment]
![immagine](https://user-images.githubusercontent.com/36633995/97757304-bffc5d00-1afc-11eb-95ca-5d73bcdca351.png)

Modificati la grandezza dei campi input.

**Comment by AlexandroVassallo** [comment]
Inserito campo errore "Inserire VM"
