### ISSUE TITLE
Reazione tasto "Aggiorna" dialog "Crea/modifica modello"

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#11]
Se si preme aggiorna l'operazione viene eseguita ma l'utente non ha nessun feedback, in quanto la dialog rimane aperta e non compare nessun messaggio di azione avvenuta con successo

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by SalvoRusso8** [comment]
Verificato
