### ISSUE TITLE
Bug aggiunta consegna in un corso

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#12]
![chrome-capture](https://user-images.githubusercontent.com/52396149/97162971-3c4f1300-1780-11eb-8e06-9f78b3941ab3.gif)

Se non si inserisce l'immagine della consegna, viene mostrato il messaggio d'errore ma è come se prendesse lo stesso il click su "Invia"

**Comment by SalvoRusso8** [comment]
Verificato
