### ISSUE TITLE
Avatar nella dialog di registrazione

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#13]
Lo spazio bianco dove comparirà l'avatar è brutto da vedere, si potrebbe mettere un'immagine di default giusto per far capire che lì andrà messo un avatar. Metto il link di un avatar da caricare.
https://bit.ly/31Iwp54

![image](https://user-images.githubusercontent.com/61883800/97164605-ac5e9880-1782-11eb-8351-5fa2d9cada20.png)

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by SalvoRusso8** [comment]
Verificato
