### ISSUE TITLE
Aggiunta studenti al corso da CSV #2

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#16]
A volte dopo la selezione del file la richiesta non viene inviata al server. Controllare questo problema e magari aggiungere un messaggio di successo o fallimento (più dettagliato possibile, specificare il motivo del fallimento) dopo aver selezionato il file

**Comment by SalvoRusso8** [comment]
Sostituire nell'alert il messaggio di errore con quello ricevuto dal server

**Comment by jackgorga** [comment]
Chiudo questa issue perché è ancora da fare da molte parti, farò un fix unico per tutti gli alert
