### ISSUE TITLE
Manca tabella per scelta studenti in Creazione team

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#18]
Nelle specifiche ci sono delle richieste ben definite sulla selezione degli studenti nella proposta del team, in particolare deve comparire una tabella simile a quella della aggiunta studenti al corso, dove selezionare gli studenti da invitare nel team. Bisogna sistemare tutta quella dialog, volendo facendo comparire una tabella senza aprire la dialog

**Comment by jackgorga** [comment]
Testare

**Comment by SalvoRusso8** [comment]
Problema grave, se rimuovi uno studente dopo averlo aggiunto alla proposta, non ricompare nella lista.
Problema non grave, sarebbe meglio allargare la dialog così da rendere i nomi degli studenti leggibili per intero.

**Comment by jackgorga** [comment]
Testare

**Comment by SalvoRusso8** [comment]
Opzionale: migliorare la larghezza dell'autocompletamento e rimuovere il bianco di troppo sulla destra

**Comment by AlexandroVassallo** [comment]
![immagine](https://user-images.githubusercontent.com/36633995/97758161-95130880-1afe-11eb-85ed-a23279cfe31e.png)
Che ne pensate di cosi? se volete che rimodifico riaprite
