### ISSUE TITLE
Rivedere messaggi di successo/fallimento

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#2]
![image](https://user-images.githubusercontent.com/52396149/97152676-87155e80-1771-11eb-8bd2-027c0a21733c.png)

Ad esempio, si potrebbe spostare la scritta e metterla "più in alto" e non sopra l'immagine della ragazza. Anche non colorato andrebbe bene

**Comment by AlexandroVassallo** [comment]
Fixato

**Comment by ValeMargi** [comment]
@AlexandroVassallo 
![image](https://user-images.githubusercontent.com/52396149/97164138-f85d0d80-1781-11eb-9229-7029f0fe317f.png)
Va bene la posizione ma bisogna aggiustare il colore. Nello screen che ti allego ( e che avevo già inviato) c'è un messaggio di errore con il colore verde.

**Comment by AlexandroVassallo** [comment]
fixato

**Comment by SalvoRusso8** [comment]
Verificato
