### ISSUE TITLE
Problema dialog login e bottone Logout 

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#20]
![loginerror](https://user-images.githubusercontent.com/52396149/97172538-71169680-178f-11eb-8ffd-929cd0c27037.gif)
 La dialog Login rimane sulla homePage anche dopo essersi loggati e se si fa Logout esce message alert di errore in un ciclo infinito

**Comment by AlexandroVassallo** [comment]
Completata

**Comment by SalvoRusso8** [comment]
Verificato
