### ISSUE TITLE
Problema bottone Change Password

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#21]
![image](https://user-images.githubusercontent.com/52396149/97173021-33fed400-1790-11eb-88ec-1c3fecc4e247.png)

Probabilmente il bottone dovrebbe servire a nascondere i campi cambio password ma non funziona

**Comment by jackgorga** [comment]
Inizialmente era così. Il problema è che se lo metti con una visibilità iniziale = false, il submit non riesce a beccare il valore inserito. Purtroppo credo che l'unica soluzione sia creare un component a parte dedicato. Se avanza tempo lo faccio, sennò secondo me può anche rimanere così (ovviamente quello non sarà più un button, ma una semplice scritta)

**Comment by SalvoRusso8** [comment]
ok, bisogna ricordarselo
