### ISSUE TITLE
Duplicazione corso vista studenti

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#23]
In seguito all'invio di una propose team, nella vista dello studente si è duplicato il corso. Il bug non è sistematico, refreshando il corso duplicato sparisce. Successo solo una volta per ora.

![image](https://user-images.githubusercontent.com/61883800/97297387-45101980-1852-11eb-9cb4-a2bf8f2d8463.png)

**Comment by jackgorga** [comment]
La chiudo solo per toglierla dalla lista. La tengo comunque sotto controllo, ma non mi è mai mai capitato!

**Comment by SalvoRusso8** [comment]
ok
