### ISSUE TITLE
Modifica selezione scadenza Propose team

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#24]
Sarebbe meglio lasciare libertà allo studente sulla selezione di una data di scadenza della proposta, quindi sostituire la scelta tra le settimane con un calendario da cui selezionare il giorno

**Comment by AlexandroVassallo** [comment]
Modificato e inserito calendario

**Comment by AlexandroVassallo** [comment]
Riscontrati errori sul formato del timeout, in lavorazione

**Comment by ValeMargi** [comment]
verificato
