### ISSUE TITLE
Errori creazione vm

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#25]
Il client non notifica i messaggi di errore ricevuti dal server nella creazione delle vm

**Comment by jackgorga** [comment]
Inizialmente gli errori li loggavo banalmente in console, ho poi messo dopo le alert. In questo caso c'era ancora il log, ovviamente andrò sostituendo tutti i console.log rimasti

**Comment by SalvoRusso8** [comment]
Verificato
