### ISSUE TITLE
Uppercase e lowercase nomi e cognomi studenti

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#29]
Sarebbe utile applicare anche agli studenti le operazioni fatte per i nomi corsi

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97602818-0c1ba480-1a0c-11eb-99b2-cf78d26b83a8.png)
Accettare comunque email in maiuscolo e convertirla poi in minuscolo in fase di invio.
Meno importante se il cognome ha uno spazio non rende maiuscola la lettera dopo lo spazio

**Comment by AlexandroVassallo** [comment]
Per accettare l'email in maiuscolo dovremmo mettere immagino, tutti i casi possibili in cui le lettere della stringa "studenti.polito.it" siano maiuscole o minuscole e viceversa. Non mi viene al momento una soluzione furba per far ciò, quindi accetto consigli da voi perchè il controllo lo facciamo con la stringa dopo il carattere "@" ed è molto articolato ripeto se dovessimo fare i vari casi se non poco pratico.  In questo momento sto parlando per il messaggio scritto in rosso sotto che ti blocca la registrazione se quel vincolo non è soddisfatto perchè per l'invio lato server non ci sono problema a prendere tutta la stringa e fare un toLowerCase. Ditemi voi.

**Comment by ValeMargi** [comment]
Provare con le regez

**Comment by AlexandroVassallo** [comment]
modificata L'emailValidator ma occorre un ulteriore controllo, da testare una volto inserito

**Comment by AlexandroVassallo** [comment]
ho tolto il controllo sul dominio a livello client, solo a livello di messaggio di errore nell'input

**Comment by ValeMargi** [comment]
Verificato

**Comment by ValeMargi** [comment]
Riesci a fare la stessa cosa per il Login e a inviarci poi comunque l'email in lower case

**Comment by AlexandroVassallo** [comment]
Fatto

**Comment by ValeMargi** [comment]
Verificato
