### ISSUE TITLE
flag nel link per login/registrazione

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#3]
Quando si preme sul pulsante di login o registrazione, nella barra degli indirizzi dovrebbe comparire il flag corrispondente, per tenere traccia della pagina in cui si è (era richiesto nel lab). Infatti localhost:4200/home?doLogin=true riporta alla schermata di login, ma questo link deve essere raggiunto anche quando si clicca sul pulsante di login, e se esco dal login con "Annulla", il flag dovrebbe scomparire. Idem per la registrazione

Nella foto sotto il link non va bene
![image](https://user-images.githubusercontent.com/61883800/97154574-55ea5d80-1774-11eb-9ec7-74d40b5d17e7.png)

Come dovrebbe funzionare
![9a9bdc92-63d1-407b-b7e9-7043930f2f41](https://user-images.githubusercontent.com/61883800/97155413-9d251e00-1775-11eb-8f89-3dbb6a4eb320.gif)

**Comment by jackgorga** [comment]
No. Il doLogin serve se si cerca di accedere a una route per i quali serve essere loggati, pertanto si fa il redirect a quella stessa route con il flag. L'apertura della dialog non cambia la route, perché non rappresenta uno stato diverso dell'applicazione.

**Comment by ValeMargi** [comment]
Era richiesto nel Lab, allego anche screenshot della videolezione di spiegazione del Prof del Lab5
![image](https://user-images.githubusercontent.com/52396149/97267211-154d1b80-182a-11eb-9e1c-ea6ca87454e2.png)
 In particolare, lui fa questo esempio: utente sloggato, clicca sulla sidenav bar "Studenti" e automaticamente si apre la dialog Login con la url modificata localhost:4200/home?doLogin=true e se si clicca su "Cancel" nella dialog o su un qualsiasi altro punto bianco della homepage, la dialog si chiude e la url diventa localhost:4200/home.
Stessa cosa deve succedere se si clicca sul bottone in alto a destra "LOGIN" ( 
![image](https://user-images.githubusercontent.com/52396149/97267479-85f43800-182a-11eb-8b1a-1942dde16730.png)
)

Riferimento testo lab5
![image](https://user-images.githubusercontent.com/52396149/97267226-1c742980-182a-11eb-8b59-e1512e26dda8.png)

**Comment by SalvoRusso8** [comment]
Verificato
