### ISSUE TITLE
Link riferiti a corsi non esistenti si aprono ugualmente

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#34]
Se costruisci a mano un link che fa riferimento a un corso non esistente, si apre, invece dovrebbe dare un alert di errore e rimandare alla home

**Comment by ValeMargi** [comment]
Diciamo che va aggiornata anche la vista, perche' se elimino corso AI, fa il reload a http://localhost:4200/home ma nella sidenav laterale rimane il corso Applicazioni Internet

![image](https://user-images.githubusercontent.com/52396149/97432943-07c48e00-191d-11eb-989d-365a02212ba4.png)

**Comment by jackgorga** [comment]
Ora credo sia risolto

**Comment by SalvoRusso8** [comment]
Verificato

**Comment by SalvoRusso8** [comment]
Il problema riportato da Valentina c'è ancora. Studente che viene rimosso mentre naviga nelle viste del corso riceve l'alert che è non ha accesso al corso, ma finché non refresha la pagina il nome del corso rimane nella sidebar

**Comment by jackgorga** [comment]
Lato client credo sia risolto. Non chiudo in quanto bisogna effettuare il controllo lato server

**Comment by AlexandroVassallo** [comment]
@ValeMargi @SalvoRusso8  avete modo di fare il controllo lato server?

**Comment by ValeMargi** [comment]
Facendo varie prove sembra essersi risolto, se ricapita ti avviso
