### ISSUE TITLE
Aggiungere controlli sul changePassword da Loggato

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#35]
Nella schermata per cambiare password ( quando l'utente è loggato), bisogna aggiungere i controlli per la validità della nuova password ( e quella ripetuta) <8 e >20 ( come viene fatto nel form register).
Ora come ora è possibile aggiornare la password con ad esempio "cia" ma questo poi non mi permette ovviamente di effettuare il Login

**Comment by ValeMargi** [comment]
Lo stesso controllo va aggiunto nel form per cambiare password quando l'utente non è loggato e si usa l'email per il cambia password

**Comment by SalvoRusso8** [comment]
Verificato
