### ISSUE TITLE
Bug tab nomeCorso

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#36]
![image](https://user-images.githubusercontent.com/52396149/97594875-66643780-1a03-11eb-807e-4626a84d77e2.png)

Bug, spiego il caso:
2 schede su Chrome, una con la pagina con conferma registrazione utente e un'altra con la home con utente "Valentina Margiotta" loggato. Se si torna sulla pagina con il messaggio "Registrazione su VirtualLabs avvenuta con successo
Puoi ora effettuare il login" compare il token di registrazione nella tab NomeCorso (come indicato nello screenshot)

**Comment by jackgorga** [comment]
Caso difficile da gestire, perché quel messaggio compare in base allo stato dell'app, e non credo sia richiesto gestire 2 stati diversi in base alla scheda in cui è aperta

**Comment by AlexandroVassallo** [comment]
sono d'accordo con jack avevo provato a gestirlo ma mi andava a danneggiare le viste con un solo stato quindi io direi di non considera questa ipotesi

**Comment by AlexandroVassallo** [comment]
Al momento chiudo la issue perchè entrambi io e jack sosteniamo che è una casistica molto particolare che un normale utilizzatore non dovrebbe riscontrare. ad ogni modo facciamo delle prove per vedere se riusciamo a fare un logout prima dell'aperture del link dell'email ma attualmente se pure lo abbiamo provato la soluzione non funge.
