### ISSUE TITLE
Rimuovere limite minimo di studenti per team in creazione corso

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#39]

**Comment by AlexandroVassallo** [comment]
Per rimovere intendi che togliamo proprio l'informazione? sbaglio o era richiesta nel progetto?

**Comment by SalvoRusso8** [comment]
Permettere al professore di impostare anche 1 come limite minimo, al momento è 2.

**Comment by AlexandroVassallo** [comment]
Fixato

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97878505-07623380-1d1f-11eb-976b-d2c0ee12cfbf.png)
Consentire di diminuire il numero minimo di membri anche tramite la freccia verso il basso

**Comment by AlexandroVassallo** [comment]
Risolta

**Comment by ValeMargi** [comment]
Verificato
