### ISSUE TITLE
Segnalazione problema nella dialog di registrazione

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#4]
La dialog di registrazione non comunica all'utente dove sta sbagliando, ma ritorna un generico "Errore nella registrazione". In particolare il problema sorge se si inserisce una matricola diversa rispetto a quella presente nella mail

**Comment by AlexandroVassallo** [comment]
In lavorazione..

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by SalvoRusso8** [comment]
Dopo l'alert, cliccando ok la richiesta viene inviata ugualmente al server, quindi viene segnalato nuovamente il messaggio di errore

![image](https://user-images.githubusercontent.com/61883800/97593236-c954cf00-1a01-11eb-93c5-8d593be9e377.png)

**Comment by ValeMargi** [comment]
verificato
