### ISSUE TITLE
Incoerenza utente visualizzato nella vista con utente loggato

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#42]
A volte (scenario non replicabile volontariamente) l'utente che viene visualizzato in alto a destra non corrisponde con quello effettivamente loggato

**Comment by AlexandroVassallo** [comment]
Potresti provare a spiegarmi in che casistica ti è successo?

**Comment by SalvoRusso8** [comment]
Dopo la scadenza del token, loggo con utente diverso e solo a volte si presenta questo bug

**Comment by AlexandroVassallo** [comment]
Non sono riuscito a replicare la situazione, nel caso in cui capita ppotresti mandare uno screen della console? per vedere se c'è uno messaggio che faccia capire quale sia lo stato incoerente che si presenta

**Comment by AlexandroVassallo** [comment]
@ValeMargi hai avuto modo di provare a testare se si presenta questa situazione? perchè ho fatto dei test con browser diversi facendo scadere il token e provando a vedere se di verifica loggando con un utente diverso ma non sono riuscito a vadere la comparsa del bug

**Comment by ValeMargi** [comment]
@AlexandroVassallo Per ora non mi è successo nuovamente

**Comment by AlexandroVassallo** [comment]
Per il momento chiudo se si ripresenta la apro
