### ISSUE TITLE
Manca data ultima modifica nella schermata VM

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#45]
Nella dialog aperta con "Apri VM" non viene visualizzata la data di ultima modifica

**Comment by jackgorga** [comment]
Perché manca proprio l'info nell'oggetto PhotoVM... infatti se ricordi vi avevo chiesto di metterla

**Comment by AlexandroVassallo** [comment]
State aggiungendo questa informazioen a PhotoVm?

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97982088-8c0e8980-1dd3-11eb-8e9c-84114de864f0.png)
Ancora non viene visualizzato, ma nella risposta lato server è presente

**Comment by ValeMargi** [comment]
Non è cambiato nulla

**Comment by jackgorga** [comment]
Sono un demente, l'avevo messa solo per Teacher

**Comment by ValeMargi** [comment]
Verificato
