### ISSUE TITLE
Chiusura non automatica Register dialog dopo registrazione avvenuta con successo

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#46]
![image](https://user-images.githubusercontent.com/52396149/97877937-3af08e00-1d1e-11eb-8c69-21f369e57e82.png)
Provare a chiudere automaticamente la dialog dopo tot secondi ( necessari per leggere il messaggio di successo in verde)

**Comment by AlexandroVassallo** [comment]
Risolta

**Comment by ValeMargi** [comment]
Verificato
