### ISSUE TITLE
Pulsante "Impostazione corso" rimane selezionato dopo la chiusura del form

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#47]
![image](https://user-images.githubusercontent.com/52396149/97879203-041b7780-1d20-11eb-89af-f14cdcd95168.png)

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97879269-10073980-1d20-11eb-93b4-f2a7f01cb195.png)
Dovrebbe essere così

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97974487-f4f00480-1dc7-11eb-9b74-653c9f3c4566.png)
Non proprio risolto

**Comment by AlexandroVassallo** [comment]
what?

**Comment by AlexandroVassallo** [comment]
![buttonEditCourse](https://user-images.githubusercontent.com/36633995/97976922-aba1b400-1dcb-11eb-9e27-d71772c47744.gif)

a me non risulta a questo punto penso sia qualcosa legato al tuo browser
scusa la qualità della gif fa schifo ma ad ogni modo non mi capita e ho provato con diversi browser

**Comment by ValeMargi** [comment]
Verificato
