### ISSUE TITLE
Bottone "Carica versione" rimane selezionato anche dopo l'aggiunta di una versione

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#52]
![image](https://user-images.githubusercontent.com/52396149/97884310-37610500-1d26-11eb-9a0f-5cbb4aa613d9.png)

**Comment by ValeMargi** [comment]
Lo stesso accade per il bottone "Carica Revisione" per il professore
![image](https://user-images.githubusercontent.com/52396149/97887988-e6074480-1d2a-11eb-925c-75d9795896ae.png)

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by ValeMargi** [comment]
Verificato
