### ISSUE TITLE
Inserire un bottone o trovare un'altra soluzione per far capire dove bisogna cliccare per aprire l'immagine della versione e revisione

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#53]
![image](https://user-images.githubusercontent.com/52396149/97885064-2fee2b80-1d27-11eb-8040-def44aaac14d.png)

**Comment by ValeMargi** [comment]
Inserire un bottone o trovare un'altra soluzione per far capire dove bisogna cliccare per aprire l'immagine della versione e revisione

**Comment by AlexandroVassallo** [comment]
Risolta

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/98216675-a79ba080-1f49-11eb-883f-8cefe3f8e6ba.png)
Bisogna sistemare le selezione dei bottoni.
Tutto il rettangolo con il timestamp risulta essere ancora un bottone, compare infatti la manina

**Comment by ValeMargi** [comment]
questo vale sia per Versioni sia per Revisioni

**Comment by AlexandroVassallo** [comment]
Modificato non spuntera più la mano o la selezione
