### ISSUE TITLE
Non viene visualizzato Voto/Stato dopo consegna revisione permanente

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#54]
![image](https://user-images.githubusercontent.com/52396149/97887437-36ca6d80-1d2a-11eb-8313-3e1de582ac4c.png)

**Comment by jackgorga** [comment]
Funzionante, manca solo aggiornamento stato in tempo reale

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97977400-721d7880-1dcc-11eb-9112-87210537b4ac.png)
Non ho capito?
Manca lo status permanent qui, intendi quello?

**Comment by ValeMargi** [comment]
Verificato
