### ISSUE TITLE
Manca titolo Assignment nella tabella Elaborati

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#55]
![image](https://user-images.githubusercontent.com/52396149/97888867-eeac4a80-1d2b-11eb-92a1-e90f4fa67558.png)

**Comment by jackgorga** [comment]
Per risolverlo mi serve un metodo nel ProfessorController che mi ritorni dato l'id dell'assignment il corrispondente AssignmentDTO

**Comment by AlexandroVassallo** [comment]
@ValeMargi hai modo di aggiungere il metodo richiesto da @jackgorga  in modo che aggiorno la vista?

**Comment by ValeMargi** [comment]
@AlexandroVassallo ma in quella vista viene fatta la richiesta a allHomework e avete già l'assignmentId non riuscite a recuperarlo da lì?

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/97986882-ac8e1200-1dda-11eb-8b9c-cdd210c7c4a8.png)

**Comment by AlexandroVassallo** [comment]
Risolta

**Comment by ValeMargi** [comment]
verificato
