### ISSUE TITLE
Tasto invio nelle dialog non seleziona l'opzione corretta

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#6]
Premendo invio dopo aver inserito i dati viene selezionato "Annulla" e non l'opzione di conferma

**Comment by AlexandroVassallo** [comment]
in quale dialog?

**Comment by ValeMargi** [comment]
> in quale dialog?

Un po' in tutte, questa issue è stata creata vedendo il messaggio fixato in alto su Telegram quindi può essere che alcune dialog siano state aggiustate

**Comment by AlexandroVassallo** [comment]
Sto cercando di risolvere questa issue anche se occorre adottare soluzioni diverse per le differenti dialog: giusto un riassunto

-Dialog Login ✔
-Dialog Registrazione ✘
-Dialog Crea Team✔
-Dialog Crea Corso ✔
-Dialog Modifica corso ✔✘
-Dialog Crea Vm ✘
-Dialog Aggiungi Version ✔
-Dialog Aggiungi Revisione ✔
-Dialog Modifica Vm ✘
-Dialog Crea Assignment ✔

Aggiorno tale commento e non appena vedete tutti verdi verificate il corretto funzionamento

**Comment by AlexandroVassallo** [comment]
Non sono riuscito a far comportare tutte le dialog allo stesso modo perchè dipende dal contenuto che hanno e come sono posizionati gli input e type dei bottoni. quelli con ✘ per poter realizzare il press enter occorre cambiare la layout della dialog.
Fatemi sapere cosa ne pensate quando provate

**Comment by ValeMargi** [comment]
- Per la tab Crea Corso non funziona se non si inseriscono professori
