### ISSUE TITLE
Modificare u.m. risorse

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#61]
![image](https://user-images.githubusercontent.com/52396149/98265959-ff59fc00-1f89-11eb-9838-ee2794c062c0.png)
Modificare ram e spazio disco da MB in GB

**Comment by AlexandroVassallo** [comment]
Fatto

**Comment by ValeMargi** [comment]
@AlexandroVassallo Puoi indicare i (GB) dove prima erano i (MB)

**Comment by ValeMargi** [comment]
lato Professore

**Comment by jackgorga** [comment]
Intenti la dialog Crea/Modifica modello?

**Comment by ValeMargi** [comment]
Verificato
