### ISSUE TITLE
Accesso professore a VM spenta

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#67]
Al momento non è possibile per il professore accedere a una VM che non è stata accesa da uno studente

**Comment by jackgorga** [comment]
Ho banalmente tolto il controllo lato client sulla VM accesa, per cui ora un professore può collegarsi a prescindere dallo stato. Si può valutare di aggiungere il pulsante di accensione/spegnimento anche per il professore, così come lo stato acceso/spento si può considerare valido solo per gli studenti, inteso come "se sei uno studente, devi avere il permesso di un owner per aprirla"
