### ISSUE TITLE
Aggiustare bottone "Registrati"  e "Login"

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#7]
![chrome-capture](https://user-images.githubusercontent.com/52396149/97158529-d95a7d80-1779-11eb-8eeb-74a379447858.gif)

Il bottone "Login" e "Registrati" rimangono "selezionati" dopo aver chiuso la rispettiva dialog

**Comment by AlexandroVassallo** [comment]
Risolto

**Comment by SalvoRusso8** [comment]
Verificato
