### ISSUE TITLE
bottoni rimangono selezionati

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#71]
- collegati VM (professore)

**Comment by AlexandroVassallo** [comment]
risolto

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/98787641-0eb0cd80-2400-11eb-9bad-6460903a016a.png)
Anche lato Studente Modifica VM
In generale ti consiglio di controllarli tutti sia lato studente che professore ( ma ovviamente non è grave come cosa)

**Comment by AlexandroVassallo** [comment]
Fatto
