### ISSUE TITLE
Aggiungere checkbox valori di default modello VM in creazione corso

### ISSUE THREAD

**Issue by SalvoRusso8** [ValeMargi/VirtualLabs#76]
Permettere al professore di decidere se vuole usare i valori di default del modello o se vuole impostarli manualmente. 
La checkbox è selezionata in partenza con "utilizza valori di default", se il professore toglie la spunta si apre una dialog in cui inserire i valori del modello ( N.B. non visualizzare però il box verde che c'è in modifica modello, altrimenti si hanno errori perché il corso non esiste). Ricordarsi di salvare quegli eventuali valori in locale e inviare poi tutto quando si preme il bottone crea

**Comment by AlexandroVassallo** [comment]
Modificata solo la vista

**Comment by AlexandroVassallo** [comment]
Risolta

**Comment by ValeMargi** [comment]
verificata
