### ISSUE TITLE
Sistemare aggiunta owner a livello grafico 

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#78]
![image](https://user-images.githubusercontent.com/52396149/98657411-2295fa00-2342-11eb-91f3-4bc5be6eaa40.png)
Mettere i nomi degli owner in colonna

**Comment by AlexandroVassallo** [comment]
Da controllare

**Comment by ValeMargi** [comment]
![image](https://user-images.githubusercontent.com/52396149/98942034-b0621880-24ed-11eb-9674-7c311d4b7e4b.png)
Da sistemare (lato docente e studente):
- Rendere coerente Owner e Proprietario ( metterei tutto in italiano )
- A livello grafico non è cambiata la disposizione degli studenti owner

**Comment by ValeMargi** [comment]
Verificato
