### ISSUE TITLE
Sistemare checkbox aggiungi studente corso

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#79]
![image](https://user-images.githubusercontent.com/52396149/98658519-6e956e80-2343-11eb-9092-228a6503f17f.png)
Dopo aver selezionato il bottone "Seleziona tutti gli studenti", la checkbox "classica" non funziona più

**Comment by AlexandroVassallo** [comment]
c'è qualcosa che non quadra hai impostato la visualizzazione di 6 student per page?

**Comment by ValeMargi** [comment]
si appunto per verificare il funzionamento del bottone "Clicca qui"

**Comment by AlexandroVassallo** [comment]
è quasi del tutto sistemata devo solo definire meglio lo stato [indeterminate] si accettano consigli dopo ore e ore che provo! A domani

**Comment by ValeMargi** [comment]
![chrome-capture](https://user-images.githubusercontent.com/52396149/99045135-2cfa0300-2591-11eb-9395-f4559479c5a1.gif)
Ti segnalo ancora alcune cose ( che sicuramente già sai) giusto per tenerne traccia, la master checkbox perde lo stato

**Comment by ValeMargi** [comment]
e lo stato intermediate che per ora non esiste proprio, come avevi già specificato

**Comment by ValeMargi** [comment]
![Uploading chrome-capture (1).gif…]()

**Comment by ValeMargi** [comment]
![Uploading chrome-capture (1).gif…]()

**Comment by ValeMargi** [comment]
![chrome-capture (1)](https://user-images.githubusercontent.com/52396149/99053427-40a96780-2599-11eb-8cc2-cc4cb0341ec1.gif)

**Comment by AlexandroVassallo** [comment]
Eh si sto cercando di definirlo meglio

**Comment by ValeMargi** [comment]
confermato
