### ISSUE TITLE
Problema nella notifica sulla home "Benvenuto USER su virtualLabs"

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#8]
![image](https://user-images.githubusercontent.com/52396149/97158743-28a0ae00-177a-11eb-983b-92828788aea7.png)
Non sempre viene mostrato il nome dell'utente loggato.

**Comment by AlexandroVassallo** [comment]
Dovrei averlo fixato adesso fate delle prove e riapritelo nel caso in cui si ripresenta la questione

**Comment by SalvoRusso8** [comment]
Ricaricando la pagina, il nome non compare mai. Bisogna per forza cliccare sul profilo in alto a destra per farlo comparire.

**Comment by ValeMargi** [comment]
verificato
