### ISSUE TITLE
Aggiungere specifica lab 

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#80]
![image](https://user-images.githubusercontent.com/52396149/98660850-0f852900-2346-11eb-8b69-d7cd1626f64e.png)
![image](https://user-images.githubusercontent.com/52396149/98660915-2297f900-2346-11eb-8424-1409bf17d65c.png)
Bisogna filtrare gli elaborati per stato vista docente

**Comment by ValeMargi** [comment]
Realizzare in maniera analoga il filtro per la vista Studente

**Comment by AlexandroVassallo** [comment]
Vale qui in sostanza c'è da aggiungere un filtro che permetta di filtrare gli elaborati in base al loro stato (in ordine temporale) perchè per il resto ci siamo.

**Comment by ValeMargi** [comment]
> Vale qui in sostanza c'è da aggiungere un filtro che permetta di filtrare gli elaborati in base al loro stato (in ordine temporale) perchè per il resto ci siamo.

per l'ordine temporale ci siamo, è già implementato. Serve un filtro per visualizzare gli elaborati in base allo stato, come funziona Gmail per le email lette/non lette etc

**Comment by ValeMargi** [comment]
Verificato
