### ISSUE TITLE
Problema form Modifica VM lato Studente

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#81]
![image](https://user-images.githubusercontent.com/52396149/98783592-1e2d1800-23fa-11eb-985c-44e3a63e3dc7.png)
![chrome-capture](https://user-images.githubusercontent.com/52396149/98784122-ec688100-23fa-11eb-898e-6bc7ab9e251c.gif)
C'è un problema per il campo "SPAZIO DISCO", non consente di superare il valore di 2000 ( in questo esempio specifico è il valore inserito nel Modello VM) e se decremento una volta con la freccia scende a 500 ( vecchio valore di default). Da 500 si presenta lo stesso valore non posso più incrementare con la freccia
Vedere gif per capire meglio

**Comment by AlexandroVassallo** [comment]
Adesso controllo

**Comment by AlexandroVassallo** [comment]
Risolto
