### ISSUE TITLE
Modificare valore minimo consentito per risorse modello VM

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#84]
Sia nella creazione corso e quindi modelVM sia nell'update modelVM, aggiungere un controllo (tramite ngIf ) che i valori inseriti "a mano" (e non con le frecce perche' c'è già questo controllo con il min matInput=1) per le risorse siano almeno maggiori di 0. Abbiamo aggiunto questo controllo lato server. Lato client mostrerei il messaggio rosso con mat-error "Inserire un valore maggiore di 0"

**Comment by jackgorga** [comment]
Fatto. Un'unica nota: per la parte di modifica del modello, il messaggio non è coerente nel caso in cui non ci sia nessuna VM... se vi vengono in mente suggerimenti sono ben accetti (non si può aggiungere un altro mat-error, perché il validator è sempre lo stesso)
