### ISSUE TITLE
Bug dialog creazione corso/modelVM

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#87]
![image](https://user-images.githubusercontent.com/52396149/99144876-0065ea00-266a-11eb-8caf-50efbc5e4456.png)
Se si compila tutto, si torna indietro dove ci sono i campi nome, acronimo etc e si fa nuovamente prosegui diventa sempre così

**Comment by AlexandroVassallo** [comment]
non so se si è fixato con le ultime modifiche ma a me non capita
