### ISSUE TITLE
Aggiustare messaggio confirm/reject registrazione da link email

### ISSUE THREAD

**Issue by ValeMargi** [ValeMargi/VirtualLabs#9]
![image](https://user-images.githubusercontent.com/52396149/97159384-1115f500-177b-11eb-93f8-bf4f9e63991b.png)

Andrebbe messo un messaggio generico e non "Registrazione fallita, token scaduto".
Ad esempio se clicco sul link da una finestra GoogleChrome, l'utente è ormai attivo.
Se accetto nuovamente il link da un'altra finestra web su Edge esce il messaggio "Registrazione fallita, token scaduto" perche' il token_registration non è più presente nel db ma non è scaduto. Per tale motivo, andrebbe messo un messaggio generale

**Comment by AlexandroVassallo** [comment]
Non ho capito bene la problematica potresti spiegarlo a parole diverse :)

**Comment by AlexandroVassallo** [comment]
Fatto

**Comment by SalvoRusso8** [comment]
Verificato
